INSERT INTO `users` ( `bio`, `email`, `full_name`, `password`, `photo_url`, `specialty`, `username`)
VALUES ( 'Alex is a certified fitness coach with over 15 years of experience in personal training and group fitness. Known for his dynamic workout routines and motivational coaching style, Alex has helped clients of all ages achieve their health and fitness goals.', 'alex@gmail.com', 'Alexander Dekov', '$2a$10$KyqrgGcUC36n5902FzFK.u.3o293PjsYrV7OO7Jo/kM9/aiuU87K6', 'https://sb.kaleidousercontent.com/67418/1672x1018/6463a5af0d/screenshot-2022-05-24-at-15-22-28.png', 'FITNESS', 'admin'),
       ('Jessica Lee is a leading fitness coach with a background in sports science. She specializes in creating customized fitness programs that blend strength training, cardio, and flexibility exercises, helping her clients improve their overall performance.', 'jessica@gmail.com', 'Jessica Lee', '$2a$10$KyqrgGcUC36n5902FzFK.u.3o293PjsYrV7OO7Jo/kM9/aiuU87K6', 'https://i1.wp.com/anytimefitness.qa/wp-content/uploads/2017/07/img_trainer_layla-1.png?w=1920&ssl=1', 'FITNESS', 'jessica'),
       ('CBum is a professional bodybuilding coach with a career spanning over 25 years. His in-depth knowledge of nutrition, strength training, and competition preparation has led many athletes to success on the national and international stage.', 'cbum@gmail.com', 'Christian Bumstead', '$2a$10$KyqrgGcUC36n5902FzFK.u.3o293PjsYrV7OO7Jo/kM9/aiuU87K6', 'https://www.the-sun.com/wp-content/uploads/sites/6/2022/12/chris-bumstead-celebrates-winning-classic-812558555.jpg', 'BODYBUILDING', 'cbum'),
       ('Usain Bolt is an elite running coach with a background in competitive marathon running. With over 15 years of coaching experience, he specializes in endurance training and race strategy, helping runners of all levels reach their full potential.', 'bolt@gmail.com','Usain Bolt', '$2a$10$KyqrgGcUC36n5902FzFK.u.3o293PjsYrV7OO7Jo/kM9/aiuU87K6', 'https://cdn.britannica.com/10/224310-050-C338430A/Usain-Bolt-gold-medal-4-x-100-meter-relay-Rio-de-Janeiro-Olympics-2016.jpg', 'RUNNING', 'bolt'),
       ('Natalie Brooks is an accomplished CrossFit coach with a passion for competitive fitness. Her expertise in Olympic lifting, coupled with her supportive coaching style, has helped many clients improve their athletic performance and achieve personal bests.', 'natalie@gmail.com', 'Natalie Brooks', '$2a$10$KyqrgGcUC36n5902FzFK.u.3o293PjsYrV7OO7Jo/kM9/aiuU87K6','https://images.squarespace-cdn.com/content/v1/5bbe7252f8135a471cf9d511/cf1a7b76-28bb-4473-b633-b4c55e34c1ce/allisonoutlaw.jpg', 'CROSSFIT', 'brooks'),
       ('Samantha Patel is a seasoned yoga instructor with a decade of teaching experience. Her expertise in Hatha and Vinyasa yoga, combined with her calming presence, has transformed the lives of many students, enhancing their physical and mental health.', 'samantha@gmail.com', 'Samantha Patel', '$2a$10$KyqrgGcUC36n5902FzFK.u.3o293PjsYrV7OO7Jo/kM9/aiuU87K6', 'https://imageio.forbes.com/specials-images/imageserve/6002319f3e631e0f0ecc35bc/A-young-woman-posed-sitting-on-a-green-and-red-chair-/960x0.jpg?format=jpg&width=960', 'YOGA', 'samantha'),
       ('Ronnie Coleman is a top bodybuilding coach and former champion bodybuilder. With a focus on personalized training regimens and nutritional planning, Ronnie has helped numerous clients achieve their physique goals and win prestigious bodybuilding titles.', 'ronnie@gmail.com', 'Ronnie Coleman', '$2a$10$KyqrgGcUC36n5902FzFK.u.3o293PjsYrV7OO7Jo/kM9/aiuU87K6', 'https://m.media-amazon.com/images/I/71MmCsdutZL._AC_UF894,1000_QL80_.jpg', 'BODYBUILDING', 'ronnie');

INSERT INTO `users_roles` (`user_id`, `role_id`)
VALUES
    (1, 2),
    (1, 3),
    (2, 2),
    (3, 2),
    (4, 2),
    (5, 2),
    (6, 2),
    (7, 2);

INSERT INTO `equipment` (`name`, `photo_url`, `weight`)
VALUES
    ('Barbell','https://leewarehouse.co.nz/wp-content/uploads/2023/04/rubber-weight-plates-set.png', 20),
    ('Dumbells', 'https://m.media-amazon.com/images/I/71l79xrqVfL._AC_UF1000,1000_QL80_.jpg', 12),
    ('Jumping Rope', 'https://fitatsea.com/wp-content/uploads/2015/02/61tFkhgIgTL._SL1001_-5a6a5141a18d9e00377892e8.jpg', 0),
    ('Pull-up bar','https://cdn.kingsbox.com/assets/media/products/body-weight/pull-up-bars/for-indoor-use/KB07RI-006--kb-modular-pu-bar-interior--0.jpg', 0),
    ('Kettlebell','https://www.xeniosusa.com/media/catalog/product/cache/2/image/9df78eab33525d08d6e5fb8d27136e95/x/s/xsnpkbl16_1/www.xeniosusa.com-XSNPKBL16-31.jpg', 20),
    ('Ez Curl Bar', 'https://1rm.com/cdn/shop/products/EzBarPng_800x.png?v=1604144126', 8),
    ('Medicine Ball', 'https://nwscdn.com/media/catalog/product/m/e/medicine-ball-10kg.jpg', 7);

INSERT INTO `exercises` (`name`, `description`, `intensity`, `photo_url`, `coach_id`, `equipment_id`)
VALUES
    ('Bench Press', 'Great exercise for overall development of your chest', 7, 'https://static.strengthlevel.com/images/exercises/bench-press/bench-press-800.jpg', 1, 1),
    ('Incline Dumbell Press', 'Great for building muscle and strength. The incline dumbbell press works your chest and front delts through a long range of motion and in a stable position.', 8, 'https://www.endomondo.com/wp-content/uploads/2024/02/Incline-Dumbbell-Press-.jpg', 1, 2),
    ('Pull-ups', 'A pull-up is an upper-body strength exercise. The pull-up is a closed-chain movement where the body is suspended by the hands, gripping a bar or other implement at a distance typically wider than shoulder-width, and pulled up. ', 7, 'https://cdn.shopify.com/s/files/1/0705/5432/1194/files/mikolo-pull-ups-blog-2.png?v=1693468017', 1, 4),
    ('Push ups', 'Push-ups are a basic exercise used in civilian athletic training or physical education and commonly in military physical training. Variations of push-ups, such as wide-arm, diamond push-ups target specific muscle groups and provide further challenges.', 6, 'https://static.strengthlevel.com/images/exercises/push-ups/push-ups-800.jpg', 1, null),
    ('Barbell Squat', 'A squat is a strength exercise in which the trainee lowers their hips from a standing position and then stands back up. Great exercise for overall building of the legs. Squats also help the hip muscles.', 7, 'https://static.strengthlevel.com/images/exercises/squat/squat-800.jpg', 2, 1),
    ('Kettlebell Goblet Squat', 'When it comes to simple fat-burning, its hard to beat the squat. As one of the royal compound moves, the kettlebell goblet squat builds huge lower-body strength and more powerful glutes.', 5 , 'https://hips.hearstapps.com/menshealth-uk/main/thumbs/33505/goblet-squat-kettlebell.jpg', 2, 5),
    ('Hip Thrust', 'The hip thrust exercise targets the gluteus maximus, which is the biggest muscle in your body. It also activates the hamstrings, quadriceps, and adductors.', 5, 'https://static.strengthlevel.com/images/exercises/hip-thrust/hip-thrust-800.jpg', 2, 1),
    ('Bench Press', 'Great exercise for overall development of your chest', 7, 'https://static.strengthlevel.com/images/exercises/bench-press/bench-press-800.jpg', 3, 1),
    ('Skull Crushers', 'Skull crushers — no exercise has a name more intimidating than this. They’re an excellent way to add definition and mass to the back of your arms. And with common sense and good mechanics, you can perform them safely with minimal risk of injury.', 5, 'https://training.fit/wp-content/uploads/2020/03/stirndruecken-langhantel-800x448.png', 3 , 6),
    ('Arnold Press', 'The seated Arnold press is a variation of the seated dumbbell press and an exercise utilized to build shoulder muscle size and strength. The Arnold press, named after Schwarzenegger himself, is an exercise used to target every single head of the deltoid.', 5, 'https://training.fit/wp-content/uploads/2020/03/arnold-press-2.png', 3, 2),
    ('Light Jog', 'Jogging is often defined as running at a pace less than 6 miles per hour (mph), and it has some significant benefits for people who want to improve their health without overdoing it. The benefits of jogging include heart health, weight loss, and others.', 3, 'https://static.tnn.in/thumb/msid-91587756,thumbsize-50516,width-1280,height-720,resizemode-75/91587756.jpg?quality=100', 4, null),
    ('Burpees','The burpee, a squat thrust with an additional stand between repetitions, is a full body exercise used in strength training. The movement itself is primarily an anaerobic, but when done in succession over a period can be utilized as an aerobic exercise.', 8, 'https://whatsupmag.com/downloads/65289/download/fitness1.jpg?cb=b6bfba2be144bb527a222ba66ffd8ee7&w=1000', 4, null),
    ('Rope Jumping', 'Simple and surprisingly beneficial for health, jumping rope is an easily accessible form of cardio and endurance training.', 4, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRv5iggvDtbaCpBj_Z8uGnzsI5p23ZMdr9yg&s', 4, 3),
    ('Push ups', 'Push-ups are a basic exercise used in civilian athletic training or physical education and commonly in military physical training. Variations of push-ups, such as wide-arm, diamond push-ups target specific muscle groups and provide further challenges.', 6, 'https://static.strengthlevel.com/images/exercises/push-ups/push-ups-800.jpg', 5, null),
    ('Wall Balls', 'Wall balls raise your heart rate and tone your arms, core, and glutes, making it an good cardiovascular and strength workout.', 5, 'https://cdn.shopify.com/s/files/1/1497/9682/files/1.How_to_Do_Wall_Balls.jpg?v=1671718579', 5, 7),
    ('Rope Jumping', 'Simple and surprisingly beneficial for health, jumping rope is an easily accessible form of cardio and endurance training.', 4, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRv5iggvDtbaCpBj_Z8uGnzsI5p23ZMdr9yg&s', 5, 3),
    ('Balasana','Bālāsana or Child Pose, is a kneeling asana in modern yoga as exercise. This pose works the upper body and stretches your arms, chest, legs, and back muscles', 3, 'https://www.yogicwayoflife.com/wp-content/uploads/2016/10/Balasana_Child_Pose_Yoga_Asana.jpg', 6, null),
    ('Triangle Pose', 'Triangle, which is a part of many yoga sequences helps build strength in the legs and stretches the hips, spine, chest, shoulders, groins, hamstrings and calves. It can also help increase mobility in the hips and neck.', 2, 'https://www.theyogacollective.com/wp-content/uploads/2019/10/5850642685417750730_IMG_8904-1-1200x800.jpg', 6, null),
    ('Cobra Pose', 'This back-bending pose can help strengthen the back muscles, increase spinal flexibility and stretches the chest, shoulders and abdomen.', 4, 'https://www.ekhartyoga.com/media/images/articles/content/Cobra-pose-Bhujangasana-Esther-Ekhart.jpg', 6, null),
    ('Bridge Pose', 'This is a back-bending pose that stretches the muscles of the chest, back and neck. It also builds strength in the back and hamstring muscles.', 4, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnJnpPuZ98-G8VXOpln3Y15Wdu8tDbdIDbfg&s', 6, null),
    ('Bench Press', 'Great exercise for overall development of your chest', 7, 'https://static.strengthlevel.com/images/exercises/bench-press/bench-press-800.jpg', 7, 1),
    ('Deadlift', 'The deadlift is a weight training and strength training exercise in which a loaded barbell or bar is lifted off the ground to the level of the hips, torso perpendicular to the floor, before being placed back on the ground.', 10, 'https://experiencelife.lifetime.life/wp-content/uploads/2021/08/f2-barbell-deadlift.jpg', 7, 1),
    ('Barbell Squat', 'A squat is a strength exercise in which the trainee lowers their hips from a standing position and then stands back up. Great exercise for overall building of the legs. Squats also help the hip muscles.', 7, 'https://static.strengthlevel.com/images/exercises/squat/squat-800.jpg', 7, 1),
    ('Leg Press', 'The leg press is a compound weight training exercise in which the individual pushes a weight or resistance away from them using their legs.It can help to build squat strength.', 6, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0lgZLFLsKzPDSnciS3GNSSFuHJojUJB3pTg&s', 7, null);


